import React, { ReactNode } from 'react'
import Head from "next/head"
import { Menu } from "./"
import styles from '../../styles/Layout.module.css'
import { ModalCartView } from "../Cart"

export type Props = {
    title: string,
    children?: ReactNode,
}

export default function Layout({ title, children }: Props) {
    return (
        <div>
            <Head>
                <title>{title ? ` | ${title}` : ""}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Menu />

            <div className={styles.container}>
                {children}
            </div>
            <ModalCartView />
        </div>
    )
}