import Head from "next/head"
import Menu from "./Menu"
import styles from '../styles/Layout.module.css'

export default function layout({ children, title }) {
    return (
        <div>
            <Head>
                <title>{title ? ` | ${title}` : ""}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Menu />

            <div className={styles.container}>{children}</div>
        </div>
    )
}